-- 0127 · رحلة الحريف في الصفحة الرئيسية — every word of the new sections, in the five languages.
--
-- Its test is supabase/tests/077_journey.sql (rolled back):
--   node --env-file=.env scripts/db-dry-run.mjs supabase/migrations/0127_journey.sql supabase/tests/077_journey.sql
--
-- THE OWNER'S REQUEST (2026-10-05, after approving the prototype): «ركّبهم في الصفحة الرئيسية مع النصوص في
-- الإعدادات وبالخمس لغات». The prototype held its words in a TypeScript module on purpose; this is the change
-- that moves them where the owner can reach them, and deletes that module.
--
-- FOUR LISTS AND NOT A HUNDRED KEYS. The sections repeat: eleven scenes, seven steps, ten questions, nine
-- example rows — 37 rows of two or three fields each. As individual settings that is ~100 keys and ~400
-- translation rows, and reordering a step would mean renumbering a dozen of them. They are stored the way
-- site.faq and site.quotes already are: one json setting per list, and one fully translated list per language
-- in public.translations, which is exactly what config.ts's settingValue() reads for a non-object value.
--
-- `key` AND `icon` INSIDE THE LISTS ARE NOT WORDS and must not be translated: the code looks the drawing up
-- by them (SCENE_VIEWS, GLYPHS). A translated `key` silently draws nothing. The description on each row says
-- so in the Back Office, where somebody editing the list will actually read it.

insert into public.settings (key, value, value_type, group_key, label_ar, description_ar, is_public, sort_order) values
  ('site.journey_scenes', '[{"key":"interest","title":"سجّل اهتمامك","line":"تكتب اسمك ونمرتك، وتقوللنا شنوّة تحب. التسجيل مجاني وما يلزمك بالشراء."},{"key":"offers","title":"اختار العرض","line":"تشوف العروض الموجودة فعلاً — بالصور، بالولاية وبالمساحة."},{"key":"trees","title":"اختار قدّاش زيتونة","line":"تحدّد العدد اللي يناسبك، وتشوف السعر والمساحة قبل ما تقرّر."},{"key":"visit","title":"احجز زيارتك","line":"تختار نهار يناسبك باش تمشي تشوف الأرض بعينيك."},{"key":"land","title":"زور الأرض","line":"تمشي للأرض مع الفريق، تشوف الزيتون والموقع قبل أي التزام."},{"key":"deposit","title":"خلّص العربون","line":"تثبّت اختيارك، والزيتونات اللي اخترتها تتحجز باسمك."},{"key":"contract","title":"امضي العقد","line":"عقد مكتوب يسمّي الزيتونات، المساحة والالتزامات. نسخة تبقى عندك."},{"key":"paying","title":"تابع الخلاص","line":"بالحاضر ولا بأقساط شهرية. كل دفعة مسجّلة وتشوفها وقتلي تحب."},{"key":"follow","title":"تابع مشروعك","line":"من حسابك: الزيتونات، الصور، حالة الأرض والأشغال اللي صارت."},{"key":"harvest","title":"الجني والعصر","line":"وقت الجني، الزيتون يتجنى ويمشي للمعصرة — وإنت تتابع."},{"key":"oil","title":"زيتك يوصلك","line":"زيت من زيتونك إنت، بالاسم، في آخر الموسم."}]'::jsonb, 'json', 'site', 'مراحل عرض الرحلة', 'الإحدى عشرة شاشة اللي تتبدّل في التلفون في الصفحة الرئيسية. كل مرحلة: key (ما يتبدّلش — هو اللي يختار الرسم)، title وline.', true, 5200),
  ('site.journey_steps', '[{"key":"pick-offer","label":"اختار العرض"},{"key":"pick-trees","label":"اختار مشروعك"},{"key":"visit","label":"زور الأرض"},{"key":"confirm","label":"ثبّت اختيارك"},{"key":"contract","label":"اعمل العقد"},{"key":"follow","label":"تابع مشروعك"},{"key":"oil","label":"استلم زيتك"}]'::jsonb, 'json', 'site', 'مراحل «كيفاش تخدم AgriZed؟»', 'السبعة مراحل القصيرة. key ما يتبدّلش — هو اللي يختار الأيقونة.', true, 5201),
  ('site.journey_trust', '[{"key":"what","icon":"tree","q":"شنوّة ناخذ بالضبط؟","a":"زيتونات مرقّمة باسمك، كل وحدة بمساحتها من الأرض."},{"key":"where","icon":"pin","q":"وين موجود المشروع؟","a":"أرض معروفة بولايتها ومعتمديتها، وتنجم تزورها قبل."},{"key":"which","icon":"tag","q":"كيفاش نعرف زيتوناتي؟","a":"كل زيتونة عندها رقم خاصّ بيها في العرض، مكتوب في العقد."},{"key":"papers","icon":"doc","q":"شنوّة الوثائق؟","a":"وثائق الأرض وعقدك إنت — الزوز تشوفهم قبل الإمضاء."},{"key":"contract","icon":"pen","q":"شنوّة العقد؟","a":"عقد يسمّي الزيتونات والمساحة والالتزامات، ونسخة تبقى عندك."},{"key":"pay","icon":"wallet","q":"كيفاش يتم الخلاص؟","a":"بالحاضر ولا بأقساط شهرية حسب العرض. كل دفعة مسجّلة."},{"key":"follow","icon":"screen","q":"كيفاش نتابع؟","a":"من حسابك: الصور، حالة الأرض والأشغال اللي صارت."},{"key":"visit","icon":"calendar","q":"كيفاش تتم الزيارة؟","a":"تختار نهار، والفريق يستنّاك في الأرض."},{"key":"harvest","icon":"basket","q":"الجني والعصر؟","a":"الزيتون يتجنى في وقتو ويمشي للمعصرة، والمراحل تتصوّر."},{"key":"oil","icon":"bottle","q":"كيفاش يوصلني الزيت؟","a":"في آخر الموسم، زيت من زيتونك، ونتفاهمو على التوصيل."}]'::jsonb, 'json', 'site', 'أسئلة قسم الثقة', 'العشرة أسئلة وجوابها. key وicon ما يتبدّلوش — icon هو اللي يختار الرسم.', true, 5202),
  ('site.journey_example', '[{"key":"offer","label":"اختار العرض","detail":"عرض في صفاقس"},{"key":"count","label":"اختار العدد","detail":"عشر زيتونات"},{"key":"book","label":"حجز زيارة","detail":"نهار سبت"},{"key":"visited","label":"زار الأرض","detail":"شاف الزيتون والموقع"},{"key":"deposit","label":"خلّص العربون","detail":"الزيتونات تحجزت باسمو"},{"key":"contract","label":"أمضى العقد","detail":"بالأرقام متاع زيتوناتو"},{"key":"follow","label":"تابع المشروع","detail":"من حسابو، بالصور"},{"key":"harvest","label":"تابع الجني","detail":"الزيتون مشى للمعصرة"},{"key":"oil","label":"استلم زيتو","detail":"في آخر الموسم"}]'::jsonb, 'json', 'site', 'مراحل مثال الحريف', 'التسعة مراحل متاع المثال: label وdetail.', true, 5203),
  ('ui.journey.eyebrow', to_jsonb('رحلتك مع AgriZed'::text), 'text', 'ui', 'الرحلة · الشريط الصغير', 'الشريط الصغير فوق عنوان قسم الرحلة', true, 5210),
  ('ui.journey.title', to_jsonb('من التسجيل حتى قارورة الزيت'::text), 'text', 'ui', 'الرحلة · العنوان', 'عنوان قسم الرحلة', true, 5211),
  ('ui.journey.lead', to_jsonb('هاذي الرحلة كاملة، خطوة بخطوة. شوفها قبل ما تبدا.'::text), 'text', 'ui', 'الرحلة · السطر تحت العنوان', 'السطر تحت عنوان قسم الرحلة', true, 5212),
  ('ui.journey.cta_primary', to_jsonb('ابدأ رحلتك مع AgriZed'::text), 'text', 'ui', 'الرحلة · الزرّ الأساسي', 'الزرّ الأخضر تحت عرض الرحلة', true, 5213),
  ('ui.journey.cta_offers', to_jsonb('اكتشف العروض'::text), 'text', 'ui', 'الرحلة · زرّ العروض', 'الزرّ الثاني تحت عرض الرحلة', true, 5214),
  ('ui.journey.play', to_jsonb('شغّل'::text), 'text', 'ui', 'الرحلة · زرّ التشغيل', 'زرّ التشغيل. ما يتكتبش — يقراه قارئ الشاشة', true, 5215),
  ('ui.journey.pause', to_jsonb('وقّف'::text), 'text', 'ui', 'الرحلة · زرّ الإيقاف', 'زرّ الإيقاف. ما يتكتبش', true, 5216),
  ('ui.journey.next', to_jsonb('اللي بعدو'::text), 'text', 'ui', 'الرحلة · زرّ التالي', 'زرّ المرحلة اللي بعدها. ما يتكتبش', true, 5217),
  ('ui.journey.previous', to_jsonb('اللي قبلو'::text), 'text', 'ui', 'الرحلة · زرّ السابق', 'زرّ المرحلة اللي قبلها. ما يتكتبش', true, 5218),
  ('ui.journey.step_of', to_jsonb('المرحلة {step} من {total}'::text), 'text', 'ui', 'الرحلة · عدّاد المراحل', 'عدّاد المراحل فوق شرح الشاشة. {step} رقم المرحلة و{total} عددهم الكل', true, 5219),
  ('ui.journey.progress_label', to_jsonb('التقدّم في عرض الرحلة'::text), 'text', 'ui', 'الرحلة · اسم صفّ النقاط', 'اسم صفّ النقاط لقارئ الشاشة. ما يظهرش', true, 5220),
  ('ui.journey.how_title', to_jsonb('كيفاش تخدم AgriZed؟'::text), 'text', 'ui', 'كيفاش تخدم · العنوان', 'عنوان قسم المراحل السبعة', true, 5221),
  ('ui.journey.trust_title', to_jsonb('شنوّة بالضبط باش يكون عندي؟'::text), 'text', 'ui', 'الثقة · العنوان', 'عنوان قسم الأسئلة العشرة', true, 5222),
  ('ui.journey.trust_lead', to_jsonb('كل سؤال يجي في بالك قبل ما تبدا، وجوابو في سطر.'::text), 'text', 'ui', 'الثقة · السطر تحت العنوان', 'السطر تحت عنوان قسم الأسئلة', true, 5223),
  ('ui.journey.offers_title', to_jsonb('عروض موجودة توّا'::text), 'text', 'ui', 'العروض · العنوان', 'عنوان قسم العروض في الصفحة الرئيسية', true, 5224),
  ('ui.journey.offers_lead', to_jsonb('أراضٍ حقيقية، بصورها وأرقامها. تنجم تزورها قبل أي التزام.'::text), 'text', 'ui', 'العروض · السطر تحت العنوان', 'السطر تحت عنوان قسم العروض', true, 5225),
  ('ui.journey.offers_all', to_jsonb('الكل'::text), 'text', 'ui', 'العروض · زرّ «الكل»', 'الزرّ الصغير اللي يوّدي لكتالوڨ العروض', true, 5226),
  ('ui.journey.offers_available', to_jsonb('{count} متاحة'::text), 'text', 'ui', 'العروض · شارة المتاح', 'الشارة الخضراء على بطاقة العرض. {count} عدد الزيتونات المتاحة', true, 5227),
  ('ui.journey.offers_cta', to_jsonb('شوف العرض'::text), 'text', 'ui', 'العروض · زرّ البطاقة', 'زرّ بطاقة العرض', true, 5228),
  ('ui.journey.offers_price_suffix', to_jsonb('سعر الزيتونة · ابتداءً من'::text), 'text', 'ui', 'العروض · كلام السعر', 'الكلام الصغير بحذا السعر في بطاقة العرض', true, 5229),
  ('ui.journey.fact_trees', to_jsonb('الزيتونات'::text), 'text', 'ui', 'العروض · خانة الزيتونات', 'اسم خانة عدد الزيتونات في بطاقة العرض', true, 5230),
  ('ui.journey.fact_area', to_jsonb('المساحة'::text), 'text', 'ui', 'العروض · خانة المساحة', 'اسم خانة المساحة الجملية', true, 5231),
  ('ui.journey.fact_variety', to_jsonb('الصنف'::text), 'text', 'ui', 'العروض · خانة الصنف', 'اسم خانة صنف الزيتون', true, 5232),
  ('ui.journey.fact_area_per_tree', to_jsonb('لكل زيتونة'::text), 'text', 'ui', 'العروض · خانة المساحة لكل زيتونة', 'اسم خانة المساحة لكل زيتونة', true, 5233),
  ('ui.journey.fact_age', to_jsonb('عمر الزيتون'::text), 'text', 'ui', 'العروض · خانة العمر', 'اسم خانة عمر الزيتون', true, 5234),
  ('ui.journey.fact_age_value', to_jsonb('{count} عام'::text), 'text', 'ui', 'العروض · قيمة العمر', 'قيمة خانة العمر. {count} عدد السنوات', true, 5235),
  ('ui.journey.legend_real', to_jsonb('أرض موجودة'::text), 'text', 'ui', 'العروض · «أرض موجودة»', 'في سطر التوضيح تحت العروض: اسم النوع الأوّل', true, 5236),
  ('ui.journey.legend_real_note', to_jsonb('بصورتها وأرقامها، تنجم تزورها.'::text), 'text', 'ui', 'العروض · شرح «أرض موجودة»', 'شرح «أرض موجودة» في سطر التوضيح', true, 5237),
  ('ui.journey.legend_estimate', to_jsonb('تقدير'::text), 'text', 'ui', 'العروض · «تقدير»', 'في سطر التوضيح: اسم النوع الثاني', true, 5238),
  ('ui.journey.legend_estimate_note', to_jsonb('حساب تقريبي، موش عرض.'::text), 'text', 'ui', 'العروض · شرح «تقدير»', 'شرح «تقدير» في سطر التوضيح', true, 5239),
  ('ui.journey.example_eyebrow', to_jsonb('مثال'::text), 'text', 'ui', 'المثال · الشريط الصغير', 'الشريط الصغير فوق عنوان قسم المثال', true, 5240),
  ('ui.journey.example_title', to_jsonb('محمد اختار مشروع في صفاقس'::text), 'text', 'ui', 'المثال · العنوان', 'عنوان قسم المثال. بدّل الاسم والمكان كيفما تحب', true, 5241),
  ('ui.journey.example_lead', to_jsonb('مثال توضيحي. الأرقام متاع عرض حقيقي موجود في الموقع.'::text), 'text', 'ui', 'المثال · السطر تحت العنوان', 'السطر تحت عنوان المثال', true, 5242),
  ('ui.journey.example_note', to_jsonb('محمد شخصية توضيحية — الأرض والأرقام عرض حقيقي.'::text), 'text', 'ui', 'المثال · سطر «شخصية توضيحية»', 'السطر الصغير في قاع قسم المثال. مهمّ: يقول إنّ الشخصية توضيحية', true, 5243),
  ('ui.journey.example_cta', to_jsonb('ابدأ رحلتك'::text), 'text', 'ui', 'المثال · الزرّ', 'الزرّ الذهبي في قسم المثال', true, 5244)
on conflict (key) do nothing;

insert into public.translations (entity, entity_key, field, locale, value, is_draft) values
  ('setting', 'site.journey_scenes', 'value', 'fr', '[{"key":"interest","title":"Dites-nous que ça vous intéresse","line":"Votre nom, votre numéro, ce que vous cherchez. C’est gratuit et sans engagement."},{"key":"offers","title":"Choisissez le terrain","line":"Les offres réelles — photos, gouvernorat et superficie."},{"key":"trees","title":"Choisissez le nombre d’oliviers","line":"Vous fixez le nombre, et vous voyez le prix et la surface avant de décider."},{"key":"visit","title":"Réservez votre visite","line":"Vous choisissez un jour pour aller voir le terrain de vos yeux."},{"key":"land","title":"Visitez le terrain","line":"Vous y allez avec l’équipe, vous voyez les oliviers et le lieu, avant tout engagement."},{"key":"deposit","title":"Versez l’acompte","line":"Vous confirmez, et les oliviers choisis sont réservés à votre nom."},{"key":"contract","title":"Signez le contrat","line":"Un contrat écrit qui nomme les oliviers, la surface et les engagements. Un exemplaire vous reste."},{"key":"paying","title":"Suivez les paiements","line":"Au comptant ou en mensualités. Chaque versement est enregistré et consultable."},{"key":"follow","title":"Suivez votre projet","line":"Depuis votre compte : les oliviers, les photos, l’état du terrain et les travaux faits."},{"key":"harvest","title":"La récolte et le pressage","line":"À la saison, les olives sont récoltées et portées au moulin — et vous suivez."},{"key":"oil","title":"Votre huile vous arrive","line":"L’huile de vos oliviers, à votre nom, à la fin de la saison."}]'::jsonb, true),
  ('setting', 'site.journey_scenes', 'value', 'de', '[{"key":"interest","title":"Melden Sie Ihr Interesse","line":"Name, Nummer und was Sie suchen. Kostenlos und unverbindlich."},{"key":"offers","title":"Wählen Sie das Grundstück","line":"Die wirklichen Angebote — Fotos, Gouvernorat und Fläche."},{"key":"trees","title":"Wählen Sie die Zahl der Bäume","line":"Sie bestimmen die Anzahl und sehen Preis und Fläche, bevor Sie entscheiden."},{"key":"visit","title":"Buchen Sie Ihren Besuch","line":"Sie wählen einen Tag, um das Grundstück selbst zu sehen."},{"key":"land","title":"Besuchen Sie das Grundstück","line":"Sie fahren mit dem Team hin und sehen Bäume und Lage — vor jeder Verpflichtung."},{"key":"deposit","title":"Zahlen Sie die Anzahlung","line":"Sie bestätigen, und die gewählten Bäume werden auf Ihren Namen reserviert."},{"key":"contract","title":"Unterschreiben Sie den Vertrag","line":"Ein schriftlicher Vertrag mit Bäumen, Fläche und Pflichten. Eine Ausfertigung bleibt bei Ihnen."},{"key":"paying","title":"Verfolgen Sie die Zahlungen","line":"Bar oder in Monatsraten. Jede Zahlung wird erfasst und ist einsehbar."},{"key":"follow","title":"Verfolgen Sie Ihr Projekt","line":"In Ihrem Konto: die Bäume, die Fotos, der Zustand des Grundstücks und die erledigten Arbeiten."},{"key":"harvest","title":"Ernte und Pressung","line":"Zur Saison werden die Oliven geerntet und zur Mühle gebracht — und Sie verfolgen es."},{"key":"oil","title":"Ihr Öl kommt an","line":"Öl von Ihren Bäumen, auf Ihren Namen, am Ende der Saison."}]'::jsonb, true),
  ('setting', 'site.journey_scenes', 'value', 'it', '[{"key":"interest","title":"Segnala il tuo interesse","line":"Nome, numero e cosa cerca. È gratuito e non impegna a nulla."},{"key":"offers","title":"Scelga il terreno","line":"Le offerte reali — foto, governatorato e superficie."},{"key":"trees","title":"Scelga quanti olivi","line":"Fissa il numero e vede prezzo e superficie prima di decidere."},{"key":"visit","title":"Prenoti la visita","line":"Sceglie un giorno per vedere il terreno con i suoi occhi."},{"key":"land","title":"Visiti il terreno","line":"Ci va con la squadra e vede gli olivi e il luogo, prima di ogni impegno."},{"key":"deposit","title":"Versi l’acconto","line":"Conferma, e gli olivi scelti restano riservati a suo nome."},{"key":"contract","title":"Firmi il contratto","line":"Un contratto scritto con gli olivi, la superficie e gli impegni. Una copia resta a lei."},{"key":"paying","title":"Segua i pagamenti","line":"In contanti o a rate mensili. Ogni versamento è registrato e consultabile."},{"key":"follow","title":"Segua il suo progetto","line":"Dal suo account: gli olivi, le foto, lo stato del terreno e i lavori svolti."},{"key":"harvest","title":"Raccolta e frangitura","line":"Alla stagione le olive si raccolgono e vanno al frantoio — e lei segue."},{"key":"oil","title":"Il suo olio arriva","line":"Olio dai suoi olivi, a suo nome, a fine stagione."}]'::jsonb, true),
  ('setting', 'site.journey_scenes', 'value', 'en', '[{"key":"interest","title":"Register your interest","line":"Your name, your number, what you are looking for. Free, and it commits you to nothing."},{"key":"offers","title":"Pick the land","line":"The offers that actually exist — photographs, governorate and area."},{"key":"trees","title":"Choose how many olive trees","line":"You set the number, and you see the price and the area before you decide."},{"key":"visit","title":"Book your visit","line":"You pick a day and go and see the land with your own eyes."},{"key":"land","title":"Visit the land","line":"You go with the team and see the trees and the place, before committing to anything."},{"key":"deposit","title":"Pay the deposit","line":"You confirm, and the trees you chose are held in your name."},{"key":"contract","title":"Sign the contract","line":"A written contract naming the trees, the area and the obligations. A copy stays with you."},{"key":"paying","title":"Follow the payments","line":"In full, or in monthly instalments. Every payment is recorded and you can see it whenever you like."},{"key":"follow","title":"Follow your grove","line":"From your account: the trees, the photographs, the state of the land and the work done."},{"key":"harvest","title":"Harvest and pressing","line":"In season the olives are picked and taken to the mill — and you follow it."},{"key":"oil","title":"Your oil reaches you","line":"Oil from your own trees, in your name, at the end of the season."}]'::jsonb, true),
  ('setting', 'site.journey_steps', 'value', 'fr', '[{"key":"pick-offer","label":"Choisir le terrain"},{"key":"pick-trees","label":"Choisir vos oliviers"},{"key":"visit","label":"Visiter"},{"key":"confirm","label":"Confirmer"},{"key":"contract","label":"Signer le contrat"},{"key":"follow","label":"Suivre"},{"key":"oil","label":"Recevoir votre huile"}]'::jsonb, true),
  ('setting', 'site.journey_steps', 'value', 'de', '[{"key":"pick-offer","label":"Grundstück wählen"},{"key":"pick-trees","label":"Bäume wählen"},{"key":"visit","label":"Besichtigen"},{"key":"confirm","label":"Bestätigen"},{"key":"contract","label":"Vertrag schließen"},{"key":"follow","label":"Verfolgen"},{"key":"oil","label":"Öl erhalten"}]'::jsonb, true),
  ('setting', 'site.journey_steps', 'value', 'it', '[{"key":"pick-offer","label":"Scegliere il terreno"},{"key":"pick-trees","label":"Scegliere gli olivi"},{"key":"visit","label":"Visitare"},{"key":"confirm","label":"Confermare"},{"key":"contract","label":"Firmare il contratto"},{"key":"follow","label":"Seguire"},{"key":"oil","label":"Ricevere l’olio"}]'::jsonb, true),
  ('setting', 'site.journey_steps', 'value', 'en', '[{"key":"pick-offer","label":"Pick the land"},{"key":"pick-trees","label":"Choose your trees"},{"key":"visit","label":"Visit"},{"key":"confirm","label":"Confirm"},{"key":"contract","label":"Sign the contract"},{"key":"follow","label":"Follow it"},{"key":"oil","label":"Receive your oil"}]'::jsonb, true),
  ('setting', 'site.journey_trust', 'value', 'fr', '[{"key":"what","icon":"tree","q":"Qu’est-ce que j’obtiens exactement ?","a":"Des oliviers numérotés à votre nom, chacun avec sa part de terrain."},{"key":"where","icon":"pin","q":"Où se trouve le terrain ?","a":"Un terrain identifié par son gouvernorat et sa délégation, que vous pouvez visiter avant."},{"key":"which","icon":"tag","q":"Comment reconnaître mes oliviers ?","a":"Chaque olivier porte son propre numéro dans l’offre, écrit au contrat."},{"key":"papers","icon":"doc","q":"Quels documents ?","a":"Les titres du terrain et votre contrat — vous voyez les deux avant de signer."},{"key":"contract","icon":"pen","q":"Que dit le contrat ?","a":"Il nomme les oliviers, la surface et les engagements, et un exemplaire vous reste."},{"key":"pay","icon":"wallet","q":"Comment se fait le paiement ?","a":"Au comptant ou en mensualités selon l’offre. Chaque versement est enregistré."},{"key":"follow","icon":"screen","q":"Comment suivre ?","a":"Depuis votre compte : les photos, l’état du terrain et les travaux faits."},{"key":"visit","icon":"calendar","q":"Comment se passe la visite ?","a":"Vous choisissez un jour, et l’équipe vous attend sur place."},{"key":"harvest","icon":"basket","q":"Et la récolte ?","a":"Les olives sont récoltées en saison et portées au moulin, et les étapes sont photographiées."},{"key":"oil","icon":"bottle","q":"Comment je reçois l’huile ?","a":"En fin de saison, l’huile de vos oliviers, et nous convenons de la livraison."}]'::jsonb, true),
  ('setting', 'site.journey_trust', 'value', 'de', '[{"key":"what","icon":"tree","q":"Was bekomme ich genau?","a":"Nummerierte Bäume auf Ihren Namen, jeder mit seiner Fläche."},{"key":"where","icon":"pin","q":"Wo liegt das Grundstück?","a":"Ein Grundstück mit Gouvernorat und Delegation, das Sie vorher besuchen können."},{"key":"which","icon":"tag","q":"Woran erkenne ich meine Bäume?","a":"Jeder Baum hat seine eigene Nummer im Angebot, die im Vertrag steht."},{"key":"papers","icon":"doc","q":"Welche Unterlagen?","a":"Die Papiere des Grundstücks und Ihr Vertrag — beides sehen Sie vor der Unterschrift."},{"key":"contract","icon":"pen","q":"Was steht im Vertrag?","a":"Er nennt Bäume, Fläche und Pflichten, und eine Ausfertigung bleibt bei Ihnen."},{"key":"pay","icon":"wallet","q":"Wie wird bezahlt?","a":"Bar oder in Monatsraten, je nach Angebot. Jede Zahlung wird erfasst."},{"key":"follow","icon":"screen","q":"Wie verfolge ich es?","a":"In Ihrem Konto: Fotos, Zustand des Grundstücks und erledigte Arbeiten."},{"key":"visit","icon":"calendar","q":"Wie läuft der Besuch ab?","a":"Sie wählen einen Tag, und das Team erwartet Sie vor Ort."},{"key":"harvest","icon":"basket","q":"Und die Ernte?","a":"Die Oliven werden zur Saison geerntet und zur Mühle gebracht, die Schritte werden fotografiert."},{"key":"oil","icon":"bottle","q":"Wie bekomme ich das Öl?","a":"Am Ende der Saison, Öl von Ihren Bäumen, und die Lieferung stimmen wir ab."}]'::jsonb, true),
  ('setting', 'site.journey_trust', 'value', 'it', '[{"key":"what","icon":"tree","q":"Che cosa ottengo esattamente?","a":"Olivi numerati a suo nome, ciascuno con la sua superficie."},{"key":"where","icon":"pin","q":"Dove si trova il terreno?","a":"Un terreno identificato da governatorato e delegazione, che può visitare prima."},{"key":"which","icon":"tag","q":"Come riconosco i miei olivi?","a":"Ogni olivo ha il suo numero nell’offerta, scritto nel contratto."},{"key":"papers","icon":"doc","q":"Quali documenti?","a":"I titoli del terreno e il suo contratto — vede entrambi prima di firmare."},{"key":"contract","icon":"pen","q":"Che cosa dice il contratto?","a":"Nomina gli olivi, la superficie e gli impegni, e una copia resta a lei."},{"key":"pay","icon":"wallet","q":"Come si paga?","a":"In contanti o a rate mensili secondo l’offerta. Ogni versamento è registrato."},{"key":"follow","icon":"screen","q":"Come seguo?","a":"Dal suo account: foto, stato del terreno e lavori svolti."},{"key":"visit","icon":"calendar","q":"Come avviene la visita?","a":"Sceglie un giorno e la squadra l’aspetta sul posto."},{"key":"harvest","icon":"basket","q":"E la raccolta?","a":"Le olive si raccolgono in stagione e vanno al frantoio, e le fasi sono fotografate."},{"key":"oil","icon":"bottle","q":"Come ricevo l’olio?","a":"A fine stagione, olio dai suoi olivi, e concordiamo la consegna."}]'::jsonb, true),
  ('setting', 'site.journey_trust', 'value', 'en', '[{"key":"what","icon":"tree","q":"What exactly do I get?","a":"Numbered olive trees in your name, each with its own share of the land."},{"key":"where","icon":"pin","q":"Where is the land?","a":"A plot named by its governorate and delegation, and you can go and see it first."},{"key":"which","icon":"tag","q":"How do I know which trees are mine?","a":"Every tree carries its own number in the offer, written into the contract."},{"key":"papers","icon":"doc","q":"What documents are there?","a":"The land’s papers and your own contract — you see both before you sign."},{"key":"contract","icon":"pen","q":"What is in the contract?","a":"It names the trees, the area and the obligations, and a copy stays with you."},{"key":"pay","icon":"wallet","q":"How is it paid?","a":"In full or in monthly instalments, depending on the offer. Every payment is recorded."},{"key":"follow","icon":"screen","q":"How do I follow it?","a":"From your account: the photographs, the state of the land and the work done."},{"key":"visit","icon":"calendar","q":"How does the visit work?","a":"You pick a day, and the team meets you there."},{"key":"harvest","icon":"basket","q":"What about the harvest?","a":"The olives are picked in season and taken to the mill, and the stages are photographed."},{"key":"oil","icon":"bottle","q":"How does the oil reach me?","a":"At the end of the season, oil from your own trees, and we agree the delivery."}]'::jsonb, true),
  ('setting', 'site.journey_example', 'value', 'fr', '[{"key":"offer","label":"Il choisit le terrain","detail":"Une offre à Sfax"},{"key":"count","label":"Il choisit le nombre","detail":"Dix oliviers"},{"key":"book","label":"Il réserve une visite","detail":"Un samedi"},{"key":"visited","label":"Il visite","detail":"Il voit les oliviers et le lieu"},{"key":"deposit","label":"Il verse l’acompte","detail":"Les oliviers sont réservés à son nom"},{"key":"contract","label":"Il signe le contrat","detail":"Avec les numéros de ses oliviers"},{"key":"follow","label":"Il suit le projet","detail":"Depuis son compte, en photos"},{"key":"harvest","label":"Il suit la récolte","detail":"Les olives partent au moulin"},{"key":"oil","label":"Il reçoit son huile","detail":"À la fin de la saison"}]'::jsonb, true),
  ('setting', 'site.journey_example', 'value', 'de', '[{"key":"offer","label":"Er wählt das Grundstück","detail":"Ein Angebot in Sfax"},{"key":"count","label":"Er wählt die Anzahl","detail":"Zehn Bäume"},{"key":"book","label":"Er bucht einen Besuch","detail":"Ein Samstag"},{"key":"visited","label":"Er besichtigt","detail":"Er sieht Bäume und Lage"},{"key":"deposit","label":"Er zahlt die Anzahlung","detail":"Die Bäume sind auf seinen Namen reserviert"},{"key":"contract","label":"Er unterschreibt","detail":"Mit den Nummern seiner Bäume"},{"key":"follow","label":"Er verfolgt es","detail":"In seinem Konto, mit Fotos"},{"key":"harvest","label":"Er verfolgt die Ernte","detail":"Die Oliven gehen zur Mühle"},{"key":"oil","label":"Er erhält sein Öl","detail":"Am Ende der Saison"}]'::jsonb, true),
  ('setting', 'site.journey_example', 'value', 'it', '[{"key":"offer","label":"Sceglie il terreno","detail":"Un’offerta a Sfax"},{"key":"count","label":"Sceglie il numero","detail":"Dieci olivi"},{"key":"book","label":"Prenota una visita","detail":"Un sabato"},{"key":"visited","label":"Visita","detail":"Vede gli olivi e il luogo"},{"key":"deposit","label":"Versa l’acconto","detail":"Gli olivi sono riservati a suo nome"},{"key":"contract","label":"Firma il contratto","detail":"Con i numeri dei suoi olivi"},{"key":"follow","label":"Segue il progetto","detail":"Dal suo account, con le foto"},{"key":"harvest","label":"Segue la raccolta","detail":"Le olive vanno al frantoio"},{"key":"oil","label":"Riceve il suo olio","detail":"A fine stagione"}]'::jsonb, true),
  ('setting', 'site.journey_example', 'value', 'en', '[{"key":"offer","label":"He picks the land","detail":"An offer in Sfax"},{"key":"count","label":"He chooses how many","detail":"Ten olive trees"},{"key":"book","label":"He books a visit","detail":"A Saturday"},{"key":"visited","label":"He visits","detail":"He sees the trees and the place"},{"key":"deposit","label":"He pays the deposit","detail":"The trees are held in his name"},{"key":"contract","label":"He signs the contract","detail":"With his trees’ numbers on it"},{"key":"follow","label":"He follows it","detail":"From his account, in photographs"},{"key":"harvest","label":"He follows the harvest","detail":"The olives go to the mill"},{"key":"oil","label":"He receives his oil","detail":"At the end of the season"}]'::jsonb, true),
  ('setting', 'ui.journey.eyebrow', 'value', 'fr', to_jsonb('Votre parcours avec AgriZed'::text), true),
  ('setting', 'ui.journey.eyebrow', 'value', 'de', to_jsonb('Ihr Weg mit AgriZed'::text), true),
  ('setting', 'ui.journey.eyebrow', 'value', 'it', to_jsonb('Il suo percorso con AgriZed'::text), true),
  ('setting', 'ui.journey.eyebrow', 'value', 'en', to_jsonb('Your journey with AgriZed'::text), true),
  ('setting', 'ui.journey.title', 'value', 'fr', to_jsonb('De l’inscription à la bouteille d’huile'::text), true),
  ('setting', 'ui.journey.title', 'value', 'de', to_jsonb('Von der Anmeldung bis zur Ölflasche'::text), true),
  ('setting', 'ui.journey.title', 'value', 'it', to_jsonb('Dall’iscrizione alla bottiglia d’olio'::text), true),
  ('setting', 'ui.journey.title', 'value', 'en', to_jsonb('From signing up to the bottle of oil'::text), true),
  ('setting', 'ui.journey.lead', 'value', 'fr', to_jsonb('Tout le parcours, étape par étape. Regardez-le avant de commencer.'::text), true),
  ('setting', 'ui.journey.lead', 'value', 'de', to_jsonb('Der ganze Weg, Schritt für Schritt. Sehen Sie ihn an, bevor Sie beginnen.'::text), true),
  ('setting', 'ui.journey.lead', 'value', 'it', to_jsonb('Tutto il percorso, passo per passo. Lo guardi prima di iniziare.'::text), true),
  ('setting', 'ui.journey.lead', 'value', 'en', to_jsonb('The whole journey, step by step. Watch it before you start.'::text), true),
  ('setting', 'ui.journey.cta_primary', 'value', 'fr', to_jsonb('Commencez votre parcours'::text), true),
  ('setting', 'ui.journey.cta_primary', 'value', 'de', to_jsonb('Starten Sie Ihren Weg'::text), true),
  ('setting', 'ui.journey.cta_primary', 'value', 'it', to_jsonb('Inizi il suo percorso'::text), true),
  ('setting', 'ui.journey.cta_primary', 'value', 'en', to_jsonb('Start your journey'::text), true),
  ('setting', 'ui.journey.cta_offers', 'value', 'fr', to_jsonb('Voir les offres'::text), true),
  ('setting', 'ui.journey.cta_offers', 'value', 'de', to_jsonb('Angebote ansehen'::text), true),
  ('setting', 'ui.journey.cta_offers', 'value', 'it', to_jsonb('Vedi le offerte'::text), true),
  ('setting', 'ui.journey.cta_offers', 'value', 'en', to_jsonb('See the offers'::text), true),
  ('setting', 'ui.journey.play', 'value', 'fr', to_jsonb('Lire'::text), true),
  ('setting', 'ui.journey.play', 'value', 'de', to_jsonb('Abspielen'::text), true),
  ('setting', 'ui.journey.play', 'value', 'it', to_jsonb('Avvia'::text), true),
  ('setting', 'ui.journey.play', 'value', 'en', to_jsonb('Play'::text), true),
  ('setting', 'ui.journey.pause', 'value', 'fr', to_jsonb('Pause'::text), true),
  ('setting', 'ui.journey.pause', 'value', 'de', to_jsonb('Pause'::text), true),
  ('setting', 'ui.journey.pause', 'value', 'it', to_jsonb('Pausa'::text), true),
  ('setting', 'ui.journey.pause', 'value', 'en', to_jsonb('Pause'::text), true),
  ('setting', 'ui.journey.next', 'value', 'fr', to_jsonb('Suivant'::text), true),
  ('setting', 'ui.journey.next', 'value', 'de', to_jsonb('Weiter'::text), true),
  ('setting', 'ui.journey.next', 'value', 'it', to_jsonb('Avanti'::text), true),
  ('setting', 'ui.journey.next', 'value', 'en', to_jsonb('Next'::text), true),
  ('setting', 'ui.journey.previous', 'value', 'fr', to_jsonb('Précédent'::text), true),
  ('setting', 'ui.journey.previous', 'value', 'de', to_jsonb('Zurück'::text), true),
  ('setting', 'ui.journey.previous', 'value', 'it', to_jsonb('Indietro'::text), true),
  ('setting', 'ui.journey.previous', 'value', 'en', to_jsonb('Previous'::text), true),
  ('setting', 'ui.journey.step_of', 'value', 'fr', to_jsonb('Étape {step} sur {total}'::text), true),
  ('setting', 'ui.journey.step_of', 'value', 'de', to_jsonb('Schritt {step} von {total}'::text), true),
  ('setting', 'ui.journey.step_of', 'value', 'it', to_jsonb('Fase {step} di {total}'::text), true),
  ('setting', 'ui.journey.step_of', 'value', 'en', to_jsonb('Step {step} of {total}'::text), true),
  ('setting', 'ui.journey.progress_label', 'value', 'fr', to_jsonb('Progression de la démonstration'::text), true),
  ('setting', 'ui.journey.progress_label', 'value', 'de', to_jsonb('Fortschritt der Vorführung'::text), true),
  ('setting', 'ui.journey.progress_label', 'value', 'it', to_jsonb('Avanzamento della dimostrazione'::text), true),
  ('setting', 'ui.journey.progress_label', 'value', 'en', to_jsonb('Journey demo progress'::text), true),
  ('setting', 'ui.journey.how_title', 'value', 'fr', to_jsonb('Comment fonctionne AgriZed ?'::text), true),
  ('setting', 'ui.journey.how_title', 'value', 'de', to_jsonb('Wie funktioniert AgriZed?'::text), true),
  ('setting', 'ui.journey.how_title', 'value', 'it', to_jsonb('Come funziona AgriZed?'::text), true),
  ('setting', 'ui.journey.how_title', 'value', 'en', to_jsonb('How does AgriZed work?'::text), true),
  ('setting', 'ui.journey.trust_title', 'value', 'fr', to_jsonb('Qu’est-ce que j’aurai exactement ?'::text), true),
  ('setting', 'ui.journey.trust_title', 'value', 'de', to_jsonb('Was habe ich am Ende genau?'::text), true),
  ('setting', 'ui.journey.trust_title', 'value', 'it', to_jsonb('Che cosa avrò esattamente?'::text), true),
  ('setting', 'ui.journey.trust_title', 'value', 'en', to_jsonb('What exactly will I have?'::text), true),
  ('setting', 'ui.journey.trust_lead', 'value', 'fr', to_jsonb('Chaque question qu’on se pose avant de commencer, répondue en une ligne.'::text), true),
  ('setting', 'ui.journey.trust_lead', 'value', 'de', to_jsonb('Jede Frage, die man sich vorher stellt — in einer Zeile beantwortet.'::text), true),
  ('setting', 'ui.journey.trust_lead', 'value', 'it', to_jsonb('Ogni domanda che viene in mente prima di iniziare, con una risposta in una riga.'::text), true),
  ('setting', 'ui.journey.trust_lead', 'value', 'en', to_jsonb('Every question you have before you start, answered in one line.'::text), true),
  ('setting', 'ui.journey.offers_title', 'value', 'fr', to_jsonb('Les offres disponibles'::text), true),
  ('setting', 'ui.journey.offers_title', 'value', 'de', to_jsonb('Angebote, die es jetzt gibt'::text), true),
  ('setting', 'ui.journey.offers_title', 'value', 'it', to_jsonb('Le offerte disponibili'::text), true),
  ('setting', 'ui.journey.offers_title', 'value', 'en', to_jsonb('Offers that exist today'::text), true),
  ('setting', 'ui.journey.offers_lead', 'value', 'fr', to_jsonb('Des terrains réels, avec leurs photos et leurs chiffres. Vous pouvez les visiter avant tout engagement.'::text), true),
  ('setting', 'ui.journey.offers_lead', 'value', 'de', to_jsonb('Echte Grundstücke mit Fotos und Zahlen. Sie können sie vor jeder Verpflichtung besuchen.'::text), true),
  ('setting', 'ui.journey.offers_lead', 'value', 'it', to_jsonb('Terreni reali, con foto e numeri. Può visitarli prima di ogni impegno.'::text), true),
  ('setting', 'ui.journey.offers_lead', 'value', 'en', to_jsonb('Real land, with its photographs and its figures. You can visit before committing to anything.'::text), true),
  ('setting', 'ui.journey.offers_all', 'value', 'fr', to_jsonb('Toutes'::text), true),
  ('setting', 'ui.journey.offers_all', 'value', 'de', to_jsonb('Alle'::text), true),
  ('setting', 'ui.journey.offers_all', 'value', 'it', to_jsonb('Tutte'::text), true),
  ('setting', 'ui.journey.offers_all', 'value', 'en', to_jsonb('All'::text), true),
  ('setting', 'ui.journey.offers_available', 'value', 'fr', to_jsonb('{count} disponibles'::text), true),
  ('setting', 'ui.journey.offers_available', 'value', 'de', to_jsonb('{count} verfügbar'::text), true),
  ('setting', 'ui.journey.offers_available', 'value', 'it', to_jsonb('{count} disponibili'::text), true),
  ('setting', 'ui.journey.offers_available', 'value', 'en', to_jsonb('{count} available'::text), true),
  ('setting', 'ui.journey.offers_cta', 'value', 'fr', to_jsonb('Voir l’offre'::text), true),
  ('setting', 'ui.journey.offers_cta', 'value', 'de', to_jsonb('Angebot ansehen'::text), true),
  ('setting', 'ui.journey.offers_cta', 'value', 'it', to_jsonb('Vedi l’offerta'::text), true),
  ('setting', 'ui.journey.offers_cta', 'value', 'en', to_jsonb('See the offer'::text), true),
  ('setting', 'ui.journey.offers_price_suffix', 'value', 'fr', to_jsonb('Prix par olivier · à partir de'::text), true),
  ('setting', 'ui.journey.offers_price_suffix', 'value', 'de', to_jsonb('Preis je Baum · ab'::text), true),
  ('setting', 'ui.journey.offers_price_suffix', 'value', 'it', to_jsonb('Prezzo per olivo · a partire da'::text), true),
  ('setting', 'ui.journey.offers_price_suffix', 'value', 'en', to_jsonb('Price per tree · from'::text), true),
  ('setting', 'ui.journey.fact_trees', 'value', 'fr', to_jsonb('Oliviers'::text), true),
  ('setting', 'ui.journey.fact_trees', 'value', 'de', to_jsonb('Bäume'::text), true),
  ('setting', 'ui.journey.fact_trees', 'value', 'it', to_jsonb('Olivi'::text), true),
  ('setting', 'ui.journey.fact_trees', 'value', 'en', to_jsonb('Olive trees'::text), true),
  ('setting', 'ui.journey.fact_area', 'value', 'fr', to_jsonb('Superficie'::text), true),
  ('setting', 'ui.journey.fact_area', 'value', 'de', to_jsonb('Fläche'::text), true),
  ('setting', 'ui.journey.fact_area', 'value', 'it', to_jsonb('Superficie'::text), true),
  ('setting', 'ui.journey.fact_area', 'value', 'en', to_jsonb('Area'::text), true),
  ('setting', 'ui.journey.fact_variety', 'value', 'fr', to_jsonb('Variété'::text), true),
  ('setting', 'ui.journey.fact_variety', 'value', 'de', to_jsonb('Sorte'::text), true),
  ('setting', 'ui.journey.fact_variety', 'value', 'it', to_jsonb('Varietà'::text), true),
  ('setting', 'ui.journey.fact_variety', 'value', 'en', to_jsonb('Variety'::text), true),
  ('setting', 'ui.journey.fact_area_per_tree', 'value', 'fr', to_jsonb('Par olivier'::text), true),
  ('setting', 'ui.journey.fact_area_per_tree', 'value', 'de', to_jsonb('Je Baum'::text), true),
  ('setting', 'ui.journey.fact_area_per_tree', 'value', 'it', to_jsonb('Per olivo'::text), true),
  ('setting', 'ui.journey.fact_area_per_tree', 'value', 'en', to_jsonb('Per tree'::text), true),
  ('setting', 'ui.journey.fact_age', 'value', 'fr', to_jsonb('Âge des oliviers'::text), true),
  ('setting', 'ui.journey.fact_age', 'value', 'de', to_jsonb('Alter der Bäume'::text), true),
  ('setting', 'ui.journey.fact_age', 'value', 'it', to_jsonb('Età degli olivi'::text), true),
  ('setting', 'ui.journey.fact_age', 'value', 'en', to_jsonb('Age of the trees'::text), true),
  ('setting', 'ui.journey.fact_age_value', 'value', 'fr', to_jsonb('{count} ans'::text), true),
  ('setting', 'ui.journey.fact_age_value', 'value', 'de', to_jsonb('{count} Jahre'::text), true),
  ('setting', 'ui.journey.fact_age_value', 'value', 'it', to_jsonb('{count} anni'::text), true),
  ('setting', 'ui.journey.fact_age_value', 'value', 'en', to_jsonb('{count} years'::text), true),
  ('setting', 'ui.journey.legend_real', 'value', 'fr', to_jsonb('Terrain réel'::text), true),
  ('setting', 'ui.journey.legend_real', 'value', 'de', to_jsonb('Echtes Grundstück'::text), true),
  ('setting', 'ui.journey.legend_real', 'value', 'it', to_jsonb('Terreno reale'::text), true),
  ('setting', 'ui.journey.legend_real', 'value', 'en', to_jsonb('Real land'::text), true),
  ('setting', 'ui.journey.legend_real_note', 'value', 'fr', to_jsonb('avec ses photos et ses chiffres, et vous pouvez la visiter.'::text), true),
  ('setting', 'ui.journey.legend_real_note', 'value', 'de', to_jsonb('mit Fotos und Zahlen, und Sie können es besuchen.'::text), true),
  ('setting', 'ui.journey.legend_real_note', 'value', 'it', to_jsonb('con le sue foto e i suoi numeri, e può visitarlo.'::text), true),
  ('setting', 'ui.journey.legend_real_note', 'value', 'en', to_jsonb('with its photographs and figures, and you can go and see it.'::text), true),
  ('setting', 'ui.journey.legend_estimate', 'value', 'fr', to_jsonb('Estimation'::text), true),
  ('setting', 'ui.journey.legend_estimate', 'value', 'de', to_jsonb('Schätzung'::text), true),
  ('setting', 'ui.journey.legend_estimate', 'value', 'it', to_jsonb('Stima'::text), true),
  ('setting', 'ui.journey.legend_estimate', 'value', 'en', to_jsonb('Estimate'::text), true),
  ('setting', 'ui.journey.legend_estimate_note', 'value', 'fr', to_jsonb('un calcul approximatif, pas une offre.'::text), true),
  ('setting', 'ui.journey.legend_estimate_note', 'value', 'de', to_jsonb('eine ungefähre Rechnung, kein Angebot.'::text), true),
  ('setting', 'ui.journey.legend_estimate_note', 'value', 'it', to_jsonb('un calcolo approssimativo, non un’offerta.'::text), true),
  ('setting', 'ui.journey.legend_estimate_note', 'value', 'en', to_jsonb('an approximate calculation, not an offer.'::text), true),
  ('setting', 'ui.journey.example_eyebrow', 'value', 'fr', to_jsonb('Exemple'::text), true),
  ('setting', 'ui.journey.example_eyebrow', 'value', 'de', to_jsonb('Beispiel'::text), true),
  ('setting', 'ui.journey.example_eyebrow', 'value', 'it', to_jsonb('Esempio'::text), true),
  ('setting', 'ui.journey.example_eyebrow', 'value', 'en', to_jsonb('Example'::text), true),
  ('setting', 'ui.journey.example_title', 'value', 'fr', to_jsonb('Mohamed a choisi un terrain à Sfax'::text), true),
  ('setting', 'ui.journey.example_title', 'value', 'de', to_jsonb('Mohamed hat ein Grundstück in Sfax gewählt'::text), true),
  ('setting', 'ui.journey.example_title', 'value', 'it', to_jsonb('Mohamed ha scelto un terreno a Sfax'::text), true),
  ('setting', 'ui.journey.example_title', 'value', 'en', to_jsonb('Mohamed chose a grove in Sfax'::text), true),
  ('setting', 'ui.journey.example_lead', 'value', 'fr', to_jsonb('Un exemple. Les chiffres viennent d’une offre réelle du site.'::text), true),
  ('setting', 'ui.journey.example_lead', 'value', 'de', to_jsonb('Ein Beispiel. Die Zahlen stammen aus einem echten Angebot auf der Website.'::text), true),
  ('setting', 'ui.journey.example_lead', 'value', 'it', to_jsonb('Un esempio. I numeri vengono da un’offerta reale del sito.'::text), true),
  ('setting', 'ui.journey.example_lead', 'value', 'en', to_jsonb('An illustration. The figures come from a real offer on the site.'::text), true),
  ('setting', 'ui.journey.example_note', 'value', 'fr', to_jsonb('Mohamed est un personnage d’illustration — le terrain et les chiffres sont réels.'::text), true),
  ('setting', 'ui.journey.example_note', 'value', 'de', to_jsonb('Mohamed ist eine Beispielfigur — Grundstück und Zahlen sind echt.'::text), true),
  ('setting', 'ui.journey.example_note', 'value', 'it', to_jsonb('Mohamed è un personaggio d’esempio — terreno e numeri sono reali.'::text), true),
  ('setting', 'ui.journey.example_note', 'value', 'en', to_jsonb('Mohamed is an illustration — the land and the figures are real.'::text), true),
  ('setting', 'ui.journey.example_cta', 'value', 'fr', to_jsonb('Commencer'::text), true),
  ('setting', 'ui.journey.example_cta', 'value', 'de', to_jsonb('Loslegen'::text), true),
  ('setting', 'ui.journey.example_cta', 'value', 'it', to_jsonb('Inizia'::text), true),
  ('setting', 'ui.journey.example_cta', 'value', 'en', to_jsonb('Start'::text), true)
on conflict (entity, entity_key, field, locale) do nothing;
